### ISSUE TITLE
How to run Coding WebIDE on Windows7?

### ISSUE THREAD

**Issue by cxgreat2014** [Coding/WebIDE#13]
I can't build it on my computer.

**Comment by summershrimp** [comment]
You may have some issues running on Windows7. Please try it in Linux. Perhaps you may install a Linux virtual machine.

**Comment by hackape** [comment]
@cxgreat2014 Although we will support windows platform eventually, WebIDE by design is meant to run in a linux environment, typically a server, and accessed from a web page, thus the name "Web-IDE". So windows support may not come in while. 

I'd suggest you try solve the problem yourself for now, and if you do, you're very welcome to contribute your solution back to the project. That's the spirit of open source isn't it? ;)

**Comment by tanhe123** [comment]
you can run in docker server mode. please refer to [readme](https://github.com/Coding/WebIDE)
